config:
  send_anonymous_usage_stats: False
  use_colors: True
  partial_parse: True

data_vault_project:
  outputs:
    dev:
      type: postgres
      host: "{{ env_var('DBT_HOST') }}"
      user: "{{ env_var('DBT_USER') }}"
      password: "{{ env_var('DBT_PASSWORD') }}"
      dbname: "{{ env_var('DBT_DBNAME') }}"
      schema: raw
      port: 6432
      threads: 4
#      secure: True
#      verify: False
  target: dev