version: '3.8'
services:

  dev:
    build: .
    volumes:
     - .:/usr/app/
    ports:
      - 12336:8080
    environment:
      - DBT_USER=${TF_VAR_postgresql_user}
      - DBT_PASSWORD=${TF_VAR_postgresql_password}

  superset:
    image: apache/superset
    container_name: superset
    restart: unless-stopped
    ports:
      - "8088:8088"
    environment:
      SUPERSET_DB_URI: "postgresql+psycopg2://superset:superset@postgres:5432/superset"
      SUPERSET_SECRET_KEY: ${SUPERSET_SECRET_KEY}
    depends_on:
      - postgres
      - redis
    volumes:
      - superset_home:/app/superset_home

  postgres:
    image: postgres:13
    container_name: postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: superset
      POSTGRES_USER: superset
      POSTGRES_PASSWORD: superset
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:6
    container_name: redis
    restart: unless-stopped
    ports:
      - "6379:6379"

volumes:
  superset_home:
  postgres_data:
